apiVersion: v2
dependencies:
- name: thanos
  repository: https://charts.bitnami.com/bitnami
  version: 16.0.4
- name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 20.13.4
name: thanos
version: 0
